### ISSUE TITLE
Infinite recursion on invalid argument

### ISSUE THREAD

**Issue by handicraftsman** [p-ranav/argparse#6]
Code: 

```cpp
#include <iostream>

#include <argparse.hpp>

static bool load_xss_libs = true;

int main(int argc, char** argv) {
  argparse::ArgumentParser parser("awcsclient");
  
  parser.add_argument("--bootstrap")
    .help("Do not autoload XS# libraries")
    .default_value(false)
    .implicit_value(true);

  parser.parse_args(argc, argv);

  if (parser["--bootstrap"] == true) {
    load_xss_libs = false;
  }

  std::cout << load_xss_libs << std::endl;
}
```

A piece of stack trace from GDB:

```
#2963 0x000055555555a653 in argparse::ArgumentParser::parse_args_internal (this=0x7fffffffdb80, argc=2, argv=0x5555559640d0) at /home/handicraftsman/Projects/AirWheel/vendor/argparse/include/argparse.hpp:575
#2964 0x0000555555559c10 in argparse::ArgumentParser::parse_args_internal (this=0x7fffffffdb80, aArguments=std::vector of length 2, capacity 2 = {...})
    at /home/handicraftsman/Projects/AirWheel/vendor/argparse/include/argparse.hpp:507
#2965 0x000055555555a653 in argparse::ArgumentParser::parse_args_internal (this=0x7fffffffdb80, argc=2, argv=0x555555964050) at /home/handicraftsman/Projects/AirWheel/vendor/argparse/include/argparse.hpp:575
#2966 0x0000555555559c10 in argparse::ArgumentParser::parse_args_internal (this=0x7fffffffdb80, aArguments=std::vector of length 2, capacity 2 = {...})
    at /home/handicraftsman/Projects/AirWheel/vendor/argparse/include/argparse.hpp:507
#2967 0x000055555555a653 in argparse::ArgumentParser::parse_args_internal (this=0x7fffffffdb80, argc=2, argv=0x555555963fd0) at /home/handicraftsman/Projects/AirWheel/vendor/argparse/include/argparse.hpp:575
#2968 0x0000555555559c10 in argparse::ArgumentParser::parse_args_internal (this=0x7fffffffdb80, aArguments=std::vector of length 2, capacity 2 = {...})
    at /home/handicraftsman/Projects/AirWheel/vendor/argparse/include/argparse.hpp:507
#2969 0x000055555555a653 in argparse::ArgumentParser::parse_args_internal (this=0x7fffffffdb80, argc=2, argv=0x555555963f50) at /home/handicraftsman/Projects/AirWheel/vendor/argparse/include/argparse.hpp:575
#2970 0x0000555555559c10 in argparse::ArgumentParser::parse_args_internal (this=0x7fffffffdb80, aArguments=std::vector of length 2, capacity 2 = {...})
    at /home/handicraftsman/Projects/AirWheel/vendor/argparse/include/argparse.hpp:507
```

**Comment by p-ranav** [comment]
I've pushed a fix for this. Please confirm and close.

**Comment by handicraftsman** [comment]
Okay, let me check

**Comment by handicraftsman** [comment]
Yes, it works, closing the issue now.
